name: Code Scan and Analysis

on:
  push:
    branches:
      - main

jobs:
  code-quality:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'  # Adjust to your .NET SDK version
      
      - name: Install Roslyn Analyzers
        run: dotnet new tool-manifest
             && dotnet tool install Microsoft.CodeAnalysis.NetAnalyzers --version 7.1.0 --tool-path .dotnet/tools

      - name: Run Roslyn Analyzers
        run: dotnet analyze

      - name: Install dotnet-secure
        run: dotnet tool install -g dotnet-secure

      - name: Run Security Code Scan
        run: dotnet-secure scan --severity High --quiet

      - name: Install StyleCop
        run: dotnet add package StyleCop.Analyzers --version 3.1.2

      - name: Run StyleCop
        run: dotnet build /p:StyleCopEnabled=true /p:StyleCopConfig=stylecop.json

      - name: Upload to CodeClimate
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CODECLIMATE_ACCESS_TOKEN }}
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
          ./cc-test-reporter before-build
          dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
          ./cc-test-reporter format-coverage -t opencover -o codeclimate.json
          ./cc-test-reporter upload-coverage -i codeclimate.json

