name: SonarQube Analysis

on:
  push:
    branches:
      - main  # adjust this to your main branch name
  pull_request:
    branches:
      - main  # adjust this to your main branch name

jobs:
  sonarqube-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.x'  # specify the .NET SDK version you are using

      - name: Install SonarScanner for .NET
        run: dotnet tool install --global dotnet-sonarscanner

      - name: SonarQube Scan
        run: |
          dotnet-sonarscanner begin /k:"IP_API" /d:sonar.login="${{ secrets.SONARQUBE_TOKEN }}" /d:sonar.host.url="http://localhost:9000"
          dotnet build
          dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONARQUBE_TOKEN }}"

      - name: Upload SonarQube Analysis
        if: always()
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}

